### ISSUE TITLE
Use webpack's built-in logging interface

### ISSUE THREAD

**Issue by beaniemonk** [Kooneko/livereload-webpack-plugin#2]
Thanks for this fork.

Since you've made some improvements already, I'd like to suggest using webpack's built-in logger interface instead of `console.log` and `console.error`: https://webpack.js.org/api/logging/#examples-of-how-to-get-and-use-webpack-logger-in-loaders-and-plugins

There is also a minor issue with the `quiet` option -- it's checking `!err || !this.options.quiet` and I believe you want `!err && !this.options.quiet`.

The two things combined make `--progress` get a little out of whack and leave behind an artifact that overlaps your message. And there's no workaround due to that issue with the `quiet` option.

![Capture](https://user-images.githubusercontent.com/1709265/104694192-d1efa400-56d8-11eb-9518-2bc403d6bd13.PNG)

It's just cosmetic, I know.

**Comment by TiTnOuK** [comment]
Thank you for your feedback :)
It's fixed in [v1.2.1](https://github.com/Kooneko/livereload-webpack-plugin/releases/tag/v1.2.1)
